-- ─────────────────────────────────────────────────────────────
-- Plugin index
-- ─────────────────────────────────────────────────────────────
-- Plugins are grouped by purpose into their own files in this
-- directory. Lazy.nvim's `{ import = "plugins" }` (see init.lua at
-- the config root) automatically loads every file here, so each
-- module just needs to return a plugin spec (or a list of them):
--
--   colorschemes.lua  → themes
--   lsp.lua           → LSP + diagnostics
--   completion.lua    → blink.cmp, snippets
--   treesitter.lua    → treesitter, autotag
--   coding.lua        → comments, autopairs, harpoon
--   telescope.lua     → fuzzy finder + extensions
--   editor.lua        → file tree, cloak, tmux navigation
--   git.lua           → gitsigns
--   formatting.lua    → conform
--   ui.lua            → noice, diagnostics UI, discord presence
--   markdown.lua      → markview, markdown preview
--   lang.lua          → language specific plugins
--   database.lua      → dadbod + pg-docker
--   todo.lua          → todo-comments, todos.nvim
--   misc.lua          → everything else
--
-- This file is kept intentionally empty so the index lives in one
-- obvious place; add new plugins to the matching module above.

return {}
